In [127]:
import pandas as pd

# Preparation

In [128]:
# Import traffic data
df_combined = pd.read_csv("data/combined_h1_2012_2024.csv")
df_combined.head()

                    Datetime                 Location    NO2     O3    PM10  Location_Code     Hr  RainDur     T   WVv  StrGlo  Year  n_vehicles        Date      Time  Month  Weekday
0  2011-12-31 23:00:00+00:00   Zch_Rosengartenstrasse    NaN    NaN     NaN            NaN    NaN      NaN   NaN   NaN     NaN  2012        1025  2011-12-31  23:00:00     12        5
1  2011-12-31 23:00:00+00:00      Zch_Schimmelstrasse  39.96  19.17  118.61            2.0  90.84     6.27  7.92  0.35     NaN  2012         545  2011-12-31  23:00:00     12        5
2  2011-12-31 23:00:00+00:00  Zch_Stampfenbachstrasse  27.08  23.22   57.15            3.0  94.18    60.00  7.25  0.40    0.01  2012         359  2011-12-31  23:00:00     12        5
3  2012-01-01 00:00:00+00:00   Zch_Rosengartenstrasse    NaN    NaN     NaN            NaN    NaN      NaN   NaN   NaN     NaN  2012        2006  2012-01-01  00:00:00      1        6
4  2012-01-01 00:00:00+00:00      Zch_Schimmelstrasse  37.33  25.80   78.63            2.0  87.87     0.12  8.48  0.59     NaN  2012        1096  2012-01-01  00:00:00      1        6

In [129]:
# Add day and re-arrange the columns
df_combined["Day"] = df_combined["Date"].str[-2:]
df_combined = df_combined[["Datetime", "Date", "Year", "Month", "Day", "Time", "Weekday",
                           "Location", "Location_Code",
                           "NO2", "O3", "PM10",
                           "Hr", "RainDur", "T", "WVv", "StrGlo",
                           "n_vehicles"]]
df_combined.head()

                    Datetime        Date  Year  Month Day      Time  Weekday                 Location  Location_Code    NO2     O3    PM10     Hr  RainDur     T   WVv  StrGlo  n_vehicles
0  2011-12-31 23:00:00+00:00  2011-12-31  2012     12  31  23:00:00        5   Zch_Rosengartenstrasse            NaN    NaN    NaN     NaN    NaN      NaN   NaN   NaN     NaN        1025
1  2011-12-31 23:00:00+00:00  2011-12-31  2012     12  31  23:00:00        5      Zch_Schimmelstrasse            2.0  39.96  19.17  118.61  90.84     6.27  7.92  0.35     NaN         545
2  2011-12-31 23:00:00+00:00  2011-12-31  2012     12  31  23:00:00        5  Zch_Stampfenbachstrasse            3.0  27.08  23.22   57.15  94.18    60.00  7.25  0.40    0.01         359
3  2012-01-01 00:00:00+00:00  2012-01-01  2012      1  01  00:00:00        6   Zch_Rosengartenstrasse            NaN    NaN    NaN     NaN    NaN      NaN   NaN   NaN     NaN        2006
4  2012-01-01 00:00:00+00:00  2012-01-01  2012      1  01  00:00:00        6      Zch_Schimmelstrasse            2.0  37.33  25.80   78.63  87.87     0.12  8.48  0.59     NaN        1096

In [130]:
# Filter out columns for NaN analysis
df_focused_nan = df_combined[["Year", "Month", "Day", "Time", "Weekday",
                              "Location",
                              "NO2", "O3", "PM10",
                              "Hr", "RainDur", "T", "WVv", "StrGlo",
                              "n_vehicles"]]
df_focused_nan.head()

   Year  Month Day      Time  Weekday                 Location    NO2     O3    PM10     Hr  RainDur     T   WVv  StrGlo  n_vehicles
0  2012     12  31  23:00:00        5   Zch_Rosengartenstrasse    NaN    NaN     NaN    NaN      NaN   NaN   NaN     NaN        1025
1  2012     12  31  23:00:00        5      Zch_Schimmelstrasse  39.96  19.17  118.61  90.84     6.27  7.92  0.35     NaN         545
2  2012     12  31  23:00:00        5  Zch_Stampfenbachstrasse  27.08  23.22   57.15  94.18    60.00  7.25  0.40    0.01         359
3  2012      1  01  00:00:00        6   Zch_Rosengartenstrasse    NaN    NaN     NaN    NaN      NaN   NaN   NaN     NaN        2006
4  2012      1  01  00:00:00        6      Zch_Schimmelstrasse  37.33  25.80   78.63  87.87     0.12  8.48  0.59     NaN        1096

# NaN overview yearly

In [131]:
nan_overview = (
    df_focused_nan
        .groupby(["Year", "Location"])
        .agg(lambda col: col.isna().sum())
        .reset_index()
)

nan_overview

    Year                 Location  Month  Day  Time  Weekday   NO2    O3  PM10    Hr  RainDur     T   WVv  StrGlo  n_vehicles
0   2012   Zch_Rosengartenstrasse      0    0     0        0  8784  8784  8784  8784     8784  8784  8784    8784           0
1   2012      Zch_Schimmelstrasse      0    0     0        0    96    86   252    27        5    27     9    8784           0
2   2012  Zch_Stampfenbachstrasse      0    0     0        0    45    29   302     9        3     9     3       3           0
3   2013   Zch_Rosengartenstrasse      0    0     0        0  6629  6628  6754  6756     6616  6756  8760    8760           0
4   2013      Zch_Schimmelstrasse      0    0     0        0    99    67   119    28        4    28     4    8760           0
5   2013  Zch_Stampfenbachstrasse      0    0     0        0    49    24   192    16        3    16    10       3           0
6   2014   Zch_Rosengartenstrasse      0    0     0        0    73    99   373     3        1     3  8760    8760           0
7   2014      Zch_Schimmelstrasse      0    0     0        0    91    57    52    22        2    22     8    8760           0
8   2014  Zch_Stampfenbachstrasse      0    0     0        0    53    82   213   103        6    57     6       6           0
9   2015   Zch_Rosengartenstrasse      0    0     0        0   179   149   154    80       76    80  3579    8760           0
10  2015      Zch_Schimmelstrasse      0    0     0        0   236   336   271   177      163   177   173    8760           0
11  2015  Zch_Stampfenbachstrasse      0    0     0        0    63    44   431    16       32    16    34      32           0
12  2016   Zch_Rosengartenstrasse      0    0     0        0   191   332   223   256      118   256   427    8784           0
13  2016      Zch_Schimmelstrasse      0    0     0        0    88    69    97    24       11    24    13    8784           0
14  2016  Zch_Stampfenbachstrasse      0    0     0        0    62    54   237    25       21    25    24      21           0
15  2017   Zch_Rosengartenstrasse      0    0     0        0    70    44    71    22        0    22   434    8760           0
16  2017      Zch_Schimmelstrasse      0    0     0        0   116   120    80    22       12    22    20    8760           0
17  2017  Zch_Stampfenbachstrasse      0    0     0        0    44    32    84    17       16    18    17      16           0
18  2018   Zch_Rosengartenstrasse      0    0     0        0   153   389    97    88       83    88   327    8760           0
19  2018      Zch_Schimmelstrasse      0    0     0        0   175   192   135    93       92    93    95    8760           0
20  2018  Zch_Stampfenbachstrasse      0    0     0        0    51    81    97     8        9     8    10       9           0
21  2019   Zch_Rosengartenstrasse      0    0     0        0    71   118   258    18       12    18   577    8760           0
22  2019      Zch_Schimmelstrasse      0    0     0        0   137    97    48    44       42    44    49    8760           0
23  2019  Zch_Stampfenbachstrasse      0    0     0        0    56    39    25    42       14    17    15      14           0
24  2020   Zch_Rosengartenstrasse      0    0     0        0    67    91    82     4        4     4    84    8784           0
25  2020      Zch_Schimmelstrasse      0    0     0        0   280   263   293   222      218   222   212    8784           0
26  2020  Zch_Stampfenbachstrasse      0    0     0        0    93    90   109   166       29   166    20      29           0
27  2021   Zch_Rosengartenstrasse      0    0     0        0   239   215   208   719      187   719   313    8760           0
28  2021      Zch_Schimmelstrasse      0    0     0        0   120   160    57  1881       53   116    47    8760           0
29  2021  Zch_Stampfenbachstrasse      0    0     0        0    49    73   108   128        3   128     0       3           0
30  2022   Zch_Rosengartenstrasse      0    0     0        0    78    62    42    32       30    32   148    8760           0
31  2022      Zch_Schimmelstrasse      0    0     0        0    62    41    11   283        4     6     1    8760           0
32  2022  Zch_Stampfenbachstrasse      0    0     0        0    45    59   546     3        2     3     0       2           0
33  2023   Zch_Rosengartenstrasse      0    0     0        0    60    89  1739    69      132    69   269    8760           0
34  2023      Zch_Schimmelstrasse      0    0     0        0   260   240   206   200      388   200   196    8760           0
35  2023  Zch_Stampfenbachstrasse      0    0     0        0    52    55    10     5        4     5     3       4           0
36  2024   Zch_Rosengartenstrasse      0    0     0        0   850   840   837   935      989   935  1093    8784           0
37  2024      Zch_Schimmelstrasse      0    0     0        0   279    81    40    49       16    49    43    8784           0
38  2024  Zch_Stampfenbachstrasse      0    0     0        0    68    51    24    27       23    27    18      28           0
39  2025   Zch_Rosengartenstrasse      0    0     0        0    38    32     8   103        1   103     1    8760           0
40  2025      Zch_Schimmelstrasse      0    0     0        0    48    36    27     3        2     3     1    8760           0
41  2025  Zch_Stampfenbachstrasse      0    0     0        0   151    25     6    12        1    12     1       1           0

# NaN overview Monthly per location

In [132]:
# Helper function for monthy overview
def monthly_nan_overview(df_original, location):
    cols_to_check = ["NO2", "O3", "PM10", "Hr", "RainDur", "T", "WVv", "StrGlo", "n_vehicles"]
    print(location)
    df_location = df_original.loc[df_original["Location"] == location]

    for year in df_location["Year"].unique():

        df_year = df_location.loc[df_location["Year"] == year]

        # NaN count per month per column
        nan_overview = (
            df_year
            .groupby("Month")[cols_to_check]
            .apply(lambda df: df.isna().sum())
        )

        # Number of unique rows with any NaN
        unique_nan_rows = (
            df_year
            .groupby("Month")[cols_to_check]
            .apply(lambda m: m.isna().any(axis=1).sum())
            .rename("Rows_with_any_NaN")
        )

        # Possible maximum NaN per month per column
        possible_max = (
            df_year
            .groupby("Month")[cols_to_check]
            .size()
            .rename("Possible_max")
        )

        # Merge all
        merged = (
            nan_overview
            .join(unique_nan_rows)
            .join(possible_max)
        )

        print(year)
        print(merged)

## Rosengartenstrasse

In [133]:
# Adjust printed width to show everything in one line
pd.set_option("display.width", 200)
pd.set_option("display.max_columns", None)

monthly_nan_overview(df_focused_nan, "Zch_Rosengartenstrasse")

Zch_Rosengartenstrasse
2012
       NO2   O3  PM10   Hr  RainDur    T  WVv  StrGlo  n_vehicles  Rows_with_any_NaN  Possible_max
Month
1      744  744   744  744      744  744  744     744           0                744           744
2      696  696   696  696      696  696  696     696           0                696           696
3      744  744   744  744      744  744  744     744           0                744           744
4      720  720   720  720      720  720  720     720           0                720           720
5      744  744   744  744      744  744  744     744           0                744           744
6      720  720   720  720      720  720  720     720           0                720           720
7      744  744   744  744      744  744  744     744           0                744           744
8      744  744   744  744      744  744  744     744           0                744           744
9      720  720   720  720      720  720  720     720           0                720           720
10     744  744   744  744      744  744  744     744           0                744           744
11     720  720   720  720      720  720  720     720           0                720           720
12     744  744   744  744      744  744  744     744           0                744           744
2013
       NO2   O3  PM10   Hr  RainDur    T  WVv  StrGlo  n_vehicles  Rows_with_any_NaN  Possible_max
Month
1      744  744   744  744      744  744  744     744           0                744           744
2      672  672   672  672      672  672  672     672           0                672           672
3      744  744   744  744      744  744  744     744           0                744           744
4      720  720   720  720      720  720  720     720           0                720           720
5      744  744   744  744      744  744  744     744           0                744           744
6      720  720   720  720      720  720  720     720           0                720           720
7      744  744   744  744      744  744  744     744           0                744           744
8      744  744   744  744      744  744  744     744           0                744           744
9      720  720   720  720      720  720  720     720           0                720           720
10      65   64   167  201       61  201  744     744           0                744           744
11       3    4    32    0        0    0  720     720           0                720           720
12       9    8     3    3        3    3  744     744           0                744           744
2014
       NO2  O3  PM10  Hr  RainDur  T  WVv  StrGlo  n_vehicles  Rows_with_any_NaN  Possible_max
Month
1        5   5   148   0        0  0  744     744           0                744           744
2        4   3    42   0        0  0  672     672           0                672           672
3        5   5     1   0        0  0  744     744           0                744           744
4        7   4    20   0        0  0  720     720           0                720           720
5        6   5    29   0        0  0  744     744           0                744           744
6        7   3     0   0        0  0  720     720           0                720           720
7        7   7     1   0        0  0  744     744           0                744           744
8        4  53    19   1        1  1  744     744           0                744           744
9        8   4    13   0        0  0  720     720           0                720           720
10       8   4     1   2        0  2  744     744           0                744           744
11       6   3    46   0        0  0  720     720           0                720           720
12       6   3    53   0        0  0  744     744           0                744           744
2015
       NO2  O3  PM10  Hr  RainDur   T  WVv  StrGlo  n_vehicles  Rows_with_any_NaN  Possible_max
Month
1        6   3    11   0        0   0  744     744           0                744           744
2        6   3     2   2        0   2  672     672           0                672           672
3        6   5     0   0        0   0  744     744           0                744           744
4        5   3    40   0        0   0  720     720           0                720           720
5       10   7     0   0        0   0  522     744           0                744           744
6       94  92    72  71       71  71   86     720           0                720           720
7       11   4     0   0        0   0    5     744           0                744           744
8        8   8     1   1        1   1   13     744           0                744           744
9        9   4     0   1        0   1   23     720           0                720           720
10       7   6     0   0        0   0   14     744           0                744           744
11       9   7    24   1        1   1    9     720           0                720           720
12       8   7     4   4        3   4   27     744           0                744           744
2016
       NO2  O3  PM10   Hr  RainDur    T  WVv  StrGlo  n_vehicles  Rows_with_any_NaN  Possible_max
Month
1        7   4    59    2        0    2   30     744           0                744           744
2        4   2     1    1        1    1    7     696           0                696           696
3      103  99   106   94       97   94   96     744           0                744           744
4        4   3     0    0        0    0    6     720           0                720           720
5        7   3     1    0        0    0   18     744           0                744           744
6       10   6     1    1        1    1   60     720           0                720           720
7       24  22    29   32       18   32   48     744           0                744           744
8        4   9     0    0        0    0   44     744           0                744           744
9        8  89    16    0        0    0   57     720           0                720           720
10       7  83     1    1        1    1   40     744           0                744           744
11       7   6     9    0        0    0    9     720           0                720           720
12       6   6     0  125        0  125   12     744           0                744           744
2017
       NO2  O3  PM10  Hr  RainDur   T  WVv  StrGlo  n_vehicles  Rows_with_any_NaN  Possible_max
Month
1        9   4     4   0        0   0   39     744           0                744           744
2        4   2     1   0        0   0   11     672           0                672           672
3        8   7     0   0        0   0   15     744           0                744           744
4        4   2    12   1        0   1   12     720           0                720           720
5        6   4    21   0        0   0   18     744           0                744           744
6        6   4    12   0        0   0   22     720           0                720           720
7        5   4     0   1        0   1   55     744           0                744           744
8        5   4     6   0        0   0   58     744           0                744           744
9        4   3     0   0        0   0   77     720           0                720           720
10       8   4     0   0        0   0   64     744           0                744           744
11       6   3    15  20        0  20   10     720           0                720           720
12       5   3     0   0        0   0   53     744           0                744           744
2018
       NO2   O3  PM10  Hr  RainDur   T  WVv  StrGlo  n_vehicles  Rows_with_any_NaN  Possible_max
Month
1        8    4     1   0        0   0    6     744           0                744           744
2        8    4     1   1        1   1    8     672           0                672           672
3        9    6     4   0        0   0   10     744           0                744           744
4        7    7     3   3        0   3   12     720           0                720           720
5        7    3     2   1        1   1   39     744           0                744           744
6        5    3     1   1        1   1   28     720           0                720           720
7        5    6     2   1        1   1   35     744           0                744           744
8        4    2     0   0        0   0   25     744           0                744           744
9        4  230     0   0        0   0   45     720           0                720           720
10       4   34     0   0        0   0   26     744           0                744           744
11      88   86    82  80       79  80   82     720           0                720           720
12       4    4     1   1        0   1   11     744           0                744           744
2019
       NO2  O3  PM10  Hr  RainDur  T  WVv  StrGlo  n_vehicles  Rows_with_any_NaN  Possible_max
Month
1        5   3     0   2        0  2   38     744           0                744           744
2        6   4     2   0        0  0   64     672           0                672           672
3        6   6   106   3        2  3   23     744           0                744           744
4        3   3   107   0        0  0   16     720           0                720           720
5        6  73     2   2        2  2   47     744           0                744           744
6        7   1     1   0        0  0   43     720           0                720           720
7       10   9    33   5        5  5   80     744           0                744           744
8        6   4     1   2        1  2  100     744           0                744           744
9        6   4     2   0        0  0   85     720           0                720           720
10       6   4     2   2        2  2   50     744           0                744           744
11       6   5     0   0        0  0   15     720           0                720           720
12       4   2     2   2        0  2   16     744           0                744           744
2020
       NO2  O3  PM10  Hr  RainDur  T  WVv  StrGlo  n_vehicles  Rows_with_any_NaN  Possible_max
Month
1        6   4     0   0        0  0    3     744           0                744           744
2        6   3     1   0        0  0    1     696           0                696           696
3        6   5     0   0        0  0    1     744           0                744           744
4        6  52     3   1        1  1    2     720           0                720           720
5        7   5     3   3        3  3    4     744           0                744           744
6        5   5     0   0        0  0   11     720           0                720           720
7        5   2     2   0        0  0   15     744           0                744           744
8        6   2     0   0        0  0   16     744           0                744           744
9        6   3     2   0        0  0   13     720           0                720           720
10       6   3    65   0        0  0    4     744           0                744           744
11       4   4     6   0        0  0    2     720           0                720           720
12       4   3     0   0        0  0   12     744           0                744           744
2021
       NO2   O3  PM10   Hr  RainDur    T  WVv  StrGlo  n_vehicles  Rows_with_any_NaN  Possible_max
Month
1        6    4     8    0        0    0   46     744           0                744           744
2        5    2     0    0        0    0    2     672           0                672           672
3        6    4     3    1        1    1    2     744           0                744           744
4        4    2     0    0        0    0    0     720           0                720           720
5        5    3     2    0        0    0    2     744           0                744           744
6        3    3     0    0        0    0    8     720           0                720           720
7        5    3     1    1        1    1   20     744           0                744           744
8       13   12    13   11       11   11   25     744           0                744           744
9      175  173   173  703      171  703  182     720           0                720           720
10       3    2     0    0        0    0   10     744           0                744           744
11      10    5     6    3        3    3    6     720           0                720           720
12       4    2     2    0        0    0   10     744           0                744           744
2022
       NO2  O3  PM10  Hr  RainDur   T  WVv  StrGlo  n_vehicles  Rows_with_any_NaN  Possible_max
Month
1        7   6     2   2        2   2   28     744           0                744           744
2        4   2     2   0        0   0    7     672           0                672           672
3        7   3     0   0        0   0    7     744           0                744           744
4        3   2     2   0        0   0    7     720           0                720           720
5        4   3     0   0        0   0    6     744           0                744           744
6        3   2     1   0        0   0    5     720           0                720           720
7        2   3     0   0        0   0    7     744           0                744           744
8        4   2     2   0        0   0    3     744           0                744           744
9        9  10     6   7        6   7   14     720           0                720           720
10       4   2     2   0        0   0   31     744           0                744           744
11       5   2     2   0        0   0    2     720           0                720           720
12      26  25    23  23       22  23   31     744           0                744           744
2023
       NO2  O3  PM10  Hr  RainDur   T  WVv  StrGlo  n_vehicles  Rows_with_any_NaN  Possible_max
Month
1        8   7     4   3        3   3   10     744           0                744           744
2        4   2   169   1        1   1   17     672           0                672           672
3        4   4   266   2        0   2   10     744           0                744           744
4        3   4   216   5        3   5    9     720           0                720           720
5        8   7   146   3        1   3   10     744           0                744           744
6        2   3   196   1        0   1    5     720           0                720           720
7        4   2   216   0        0   0   16     744           0                744           744
8        2   1    97   2        0   2   23     744           0                744           744
9        4   9   106   8        7   8   21     720           0                720           720
10      11  37   188  21       16  21   27     744           0                744           744
11       5   4   124   6        1   6   11     720           0                720           720
12       5   9    11  17      100  17  110     744           0                744           744
2024
       NO2   O3  PM10   Hr  RainDur    T  WVv  StrGlo  n_vehicles  Rows_with_any_NaN  Possible_max
Month
1        5    6    11    0        3    0   27     744           0                744           744
2        2    2     1    0        0    0   27     696           0                696           696
3      610  613   613  610      613  610  615     744           0                744           744
4      122  115   116  233      285  233  286     720           0                720           720
5       42   40    40   40       38   40   51     744           0                744           744
6       18   16    15   14       14   14   57     720           0                720           720
7        8    8     8    6        5    6    2     744           0                744           744
8        2    2     0    0        0    0    0     744           0                744           744
9       33   32    31   31       31   31   28     720           0                720           720
10       3    2     0    1        0    1    0     744           0                744           744
11       1    2     2    0        0    0    0     720           0                720           720
12       4    2     0    0        0    0    0     744           0                744           744
2025
       NO2  O3  PM10   Hr  RainDur    T  WVv  StrGlo  n_vehicles  Rows_with_any_NaN  Possible_max
Month
1        3   2     0    0        0    0    0     744           0                744           744
2        2   1     0    0        0    0    0     672           0                672           672
3        3   2     2    0        0    0    0     744           0                744           744
4        2   2     0  102        0  102    0     720           0                720           720
5        2   3     0    0        0    0    0     744           0                744           744
6        2   1     2    0        0    0    0     720           0                720           720
7        4   4     1    0        0    0    0     744           0                744           744
8        6   4     0    0        0    0    0     744           0                744           744
9        2   1     0    0        0    0    0     720           0                720           720
10       3   3     0    0        0    0    0     744           0                744           744
11       6   5     2    0        0    0    0     720           0                720           720
12       3   4     1    1        1    1    1     744           0                744           744

## Schimmelstrasse

In [134]:
# Adjust printed width to show everything in one line
pd.set_option("display.width", 200)
pd.set_option("display.max_columns", None)

monthly_nan_overview(df_focused_nan, "Zch_Schimmelstrasse")

Zch_Schimmelstrasse
2012
       NO2  O3  PM10  Hr  RainDur   T  WVv  StrGlo  n_vehicles  Rows_with_any_NaN  Possible_max
Month
1        9   7     0   1        0   1    1     744           0                744           744
2        6   2    79   1        0   1    0     696           0                696           696
3       15  28    17   0        0   0    0     744           0                744           744
4        8   6     3   0        0   0    0     720           0                720           720
5        9   8    22   1        0   1    1     744           0                744           744
6        6   6     1   0        0   0    0     720           0                720           720
7        9   5    67   0        0   0    0     744           0                744           744
8        4   6    11   0        0   0    0     744           0                744           744
9       11   8    42  19        5  19    5     720           0                720           720
10       5   3     9   1        0   1    0     744           0                744           744
11       7   4     1   2        0   2    1     720           0                720           720
12       7   3     0   2        0   2    1     744           0                744           744
2013
       NO2  O3  PM10  Hr  RainDur  T  WVv  StrGlo  n_vehicles  Rows_with_any_NaN  Possible_max
Month
1        8   5    30   1        0  1    0     744           0                744           744
2        7   3    12   3        0  3    0     672           0                672           672
3        7   3     1   2        0  2    0     744           0                744           744
4       15  12     9   2        0  2    0     720           0                720           720
5        7   4     1   2        0  2    0     744           0                744           744
6        9   9     0   2        0  2    0     720           0                720           720
7        8   5     2   3        1  3    1     744           0                744           744
8        9   6     1   3        0  3    0     744           0                744           744
9        6   5     2   0        0  0    0     720           0                720           720
10       4   3     1   3        0  3    0     744           0                744           744
11      11   8    56   6        3  6    3     720           0                720           720
12       8   4     4   1        0  1    0     744           0                744           744
2014
       NO2  O3  PM10  Hr  RainDur  T  WVv  StrGlo  n_vehicles  Rows_with_any_NaN  Possible_max
Month
1        6   5     2   2        1  2    2     744           0                744           744
2        7   2     0   3        0  3    0     672           0                672           672
3        5   3     3   1        0  1    1     744           0                744           744
4       18   6    12   1        0  1    1     720           0                720           720
5        6   4     0   2        0  2    0     744           0                744           744
6        7   6     0   2        0  2    0     720           0                720           720
7        8   5     4   1        0  1    0     744           0                744           744
8        6   5     0   2        0  2    0     744           0                744           744
9        5   3     0   1        0  1    0     720           0                720           720
10       8   3     0   2        0  2    2     744           0                744           744
11      10  11    31   4        1  4    1     720           0                720           720
12       5   4     0   1        0  1    1     744           0                744           744
2015
       NO2   O3  PM10   Hr  RainDur    T  WVv  StrGlo  n_vehicles  Rows_with_any_NaN  Possible_max
Month
1        9    5    36    1        0    1    0     744           0                744           744
2        4    1     0    0        0    0    0     672           0                672           672
3       10    9    15    1        0    1    0     744           0                744           744
4        9    7     1    1        1    1    1     720           0                720           720
5       22   21    18   18       18   18   18     744           0                744           744
6        8  123     3    3        1    3    1     720           0                720           720
7        9    3     1    0        0    0    0     744           0                744           744
8       10    5     0    1        0    1    0     744           0                744           744
9        6    4     0    1        0    1    1     720           0                720           720
10     138  152   133  150      143  150  147     744           0                744           744
11       7    5    64    1        0    1    2     720           0                720           720
12       4    1     0    0        0    0    3     744           0                744           744
2016
       NO2  O3  PM10  Hr  RainDur  T  WVv  StrGlo  n_vehicles  Rows_with_any_NaN  Possible_max
Month
1        5   5     0   1        0  1    0     744           0                744           744
2        3   2     0   3        0  3    0     696           0                696           696
3        7   5     1   2        1  2    2     744           0                744           744
4        7   6     7   2        1  2    1     720           0                720           720
5        6   5     1   4        2  4    1     744           0                744           744
6       11   9    11   0        0  0    0     720           0                720           720
7        6   5     5   1        0  1    0     744           0                744           744
8        8   4     7   2        0  2    0     744           0                744           744
9        7   6     1   2        1  2    2     720           0                720           720
10       9   6     1   1        1  1    1     744           0                744           744
11      13  12    27   6        5  6    6     720           0                720           720
12       6   4    36   0        0  0    0     744           0                744           744
2017
       NO2  O3  PM10  Hr  RainDur  T  WVv  StrGlo  n_vehicles  Rows_with_any_NaN  Possible_max
Month
1        9   5     4   2        0  2    2     744           0                744           744
2        6   4     0   0        0  0    2     672           0                672           672
3       10   7    25   2        0  2    0     744           0                744           744
4       12  14    24   4        2  4    4     720           0                720           720
5        7   3    11   1        0  1    0     744           0                744           744
6       11   8     3   4        2  4    2     720           0                720           720
7        7   4     2   2        2  2    2     744           0                744           744
8       10  27     3   4        3  4    3     744           0                744           744
9        7   4     2   1        1  1    1     720           0                720           720
10      13  31     5   1        1  1    2     744           0                744           744
11      13   9     1   1        1  1    2     720           0                720           720
12      11   4     0   0        0  0    0     744           0                744           744
2018
       NO2  O3  PM10  Hr  RainDur   T  WVv  StrGlo  n_vehicles  Rows_with_any_NaN  Possible_max
Month
1        9   8     3   3        3   3    3     744           0                744           744
2        9  27     1   1        1   1    1     672           0                672           672
3       10  10     2   2        2   2    3     744           0                744           744
4       82  81    97  76       75  76   75     720           0                720           720
5        8  26     1   1        1   1    1     744           0                744           744
6        7   5     1   1        1   1    1     720           0                720           720
7        8   6     3   1        1   1    2     744           0                744           744
8        7   5     2   2        2   2    2     744           0                744           744
9        6   3     2   2        2   2    2     720           0                720           720
10       8   7     3   3        3   3    3     744           0                744           744
11      13  11    20   1        1   1    2     720           0                720           720
12       8   3     0   0        0   0    0     744           0                744           744
2019
       NO2  O3  PM10  Hr  RainDur   T  WVv  StrGlo  n_vehicles  Rows_with_any_NaN  Possible_max
Month
1        8   5     3   2        2   2    2     744           0                744           744
2       11   6     1   1        1   1    4     672           0                672           672
3        8   8     3   2        2   2    2     744           0                744           744
4       14   8     4   4        3   4    4     720           0                720           720
5        9   7     1   1        1   1    1     744           0                744           744
6        7   4     3   1        1   1    2     720           0                720           720
7        6   4     0   1        0   1    1     744           0                744           744
8       12   7     2   2        2   2    2     744           0                744           744
9       10   6     1   1        1   1    2     720           0                720           720
10       7   3     1   0        0   0    0     744           0                744           744
11      12   7     0   0        0   0    0     720           0                720           720
12      33  32    29  29       29  29   29     744           0                744           744
2020
       NO2   O3  PM10   Hr  RainDur    T  WVv  StrGlo  n_vehicles  Rows_with_any_NaN  Possible_max
Month
1       24   22    18   18       18   18   17     744           0                744           744
2       29   28    23   24       22   24   20     696           0                696           696
3        6    6     0    0        0    0    0     744           0                744           744
4        4    4     0    1        0    1    0     720           0                720           720
5        6    5     2    1        1    1    0     744           0                744           744
6       11    7     1    1        2    1    0     720           0                720           720
7        6    4     2    0        0    0    0     744           0                744           744
8        2    1     0    0        0    0    0     744           0                744           744
9        3    2     0    0        0    0    0     720           0                720           720
10       4    2     0    0        0    0    0     744           0                744           744
11       5    4     2    0        0    0    1     720           0                720           720
12     180  178   245  177      175  177  174     744           0                744           744
2021
       NO2  O3  PM10   Hr  RainDur   T  WVv  StrGlo  n_vehicles  Rows_with_any_NaN  Possible_max
Month
1        7   2     0    0        0   0    0     744           0                744           744
2        6   3     0    0        0   0    0     672           0                672           672
3        5   3     0    0        0   0    0     744           0                744           744
4        5   3     0    1        0   1    0     720           0                720           720
5        5   4     1   55        0  55    0     744           0                744           744
6        3   2     0    0        0   0    0     720           0                720           720
7        8   4     0    0        0   0    0     744           0                744           744
8        9   8     2    1        2   1    0     744           0                744           744
9        6  67     0    0        0   0    0     720           0                720           720
10      28  27    23  361       23  23   21     744           0                744           744
11      31  30    31  720       28  36   26     720           0                720           720
12       7   7     0  743        0   0    0     744           0                744           744
2022
       NO2  O3  PM10   Hr  RainDur  T  WVv  StrGlo  n_vehicles  Rows_with_any_NaN  Possible_max
Month
1        8   3     0  278        0  2    0     744           0                744           744
2        3   2     0    0        0  0    0     672           0                672           672
3        6   4     3    0        0  0    0     744           0                744           744
4        5   5     1    1        1  1    0     720           0                720           720
5        5   3     1    0        0  0    0     744           0                744           744
6        4   4     0    0        0  0    0     720           0                720           720
7        3   2     0    0        0  0    0     744           0                744           744
8        5   1     2    0        0  0    0     744           0                744           744
9        6   4     1    1        1  1    0     720           0                720           720
10       7   4     2    1        1  1    1     744           0                744           744
11       5   4     1    1        1  1    0     720           0                720           720
12       5   5     0    1        0  0    0     744           0                744           744
2023
       NO2   O3  PM10  Hr  RainDur   T  WVv  StrGlo  n_vehicles  Rows_with_any_NaN  Possible_max
Month
1        5    4     0   0        0   0    0     744           0                744           744
2       70   69    67  67       67  67   65     672           0                672           672
3        6    3     1   0        0   0    0     744           0                744           744
4        5    4     0   0        0   0    0     720           0                720           720
5        8    7     0   0        0   0    0     744           0                744           744
6      101  100   101  98      286  98   98     720           0                720           720
7        6    3     2   0        0   0    0     744           0                744           744
8       17   14    11  11       11  11   11     744           0                744           744
9        3    3     1   1        1   1    0     720           0                720           720
10      28   25    22  22       22  22   22     744           0                744           744
11       5    5     1   1        1   1    0     720           0                720           720
12       6    3     0   0        0   0    0     744           0                744           744
2024
       NO2  O3  PM10  Hr  RainDur   T  WVv  StrGlo  n_vehicles  Rows_with_any_NaN  Possible_max
Month
1        6   5     0   0        0   0    0     744           0                744           744
2        4   3     2   0        0   0    0     696           0                696           696
3       15  14    10  10       10  10    9     744           0                744           744
4        6   5     0   0        0   0    0     720           0                720           720
5        5   5     4   3        3   3    2     744           0                744           744
6       17  16     1  14        1  14   12     720           0                720           720
7       25  24     2  22        2  22   20     744           0                744           744
8        3   2     1   0        0   0    0     744           0                744           744
9        1   1     0   0        0   0    0     720           0                720           720
10       2   2     0   0        0   0    0     744           0                744           744
11       6   2    20   0        0   0    0     720           0                720           720
12     189   2     0   0        0   0    0     744           0                744           744
2025
       NO2  O3  PM10  Hr  RainDur  T  WVv  StrGlo  n_vehicles  Rows_with_any_NaN  Possible_max
Month
1        7   4     0   0        0  0    0     744           0                744           744
2        4   2     0   0        0  0    0     672           0                672           672
3        3   2     2   0        0  0    0     744           0                744           744
4        6   3     0   1        0  1    0     720           0                720           720
5        3   2    20   0        0  0    0     744           0                744           744
6        2   3     0   0        0  0    0     720           0                720           720
7        7   6     1   1        1  1    0     744           0                744           744
8        2   1     0   0        0  0    0     744           0                744           744
9        3   2     0   0        0  0    0     720           0                720           720
10       3   6     1   0        0  0    0     744           0                744           744
11       4   2     2   0        0  0    0     720           0                720           720
12       4   3     1   1        1  1    1     744           0                744           744

## Stampfenbachstrasse

In [135]:
# Adjust printed width to show everything in one line
pd.set_option("display.width", 200)
pd.set_option("display.max_columns", None)

monthly_nan_overview(df_focused_nan, "Zch_Stampfenbachstrasse")

Zch_Stampfenbachstrasse
2012
       NO2  O3  PM10  Hr  RainDur  T  WVv  StrGlo  n_vehicles  Rows_with_any_NaN  Possible_max
Month
1        3   2     0   0        0  0    0       0           0                  3           744
2        4   2     0   0        0  0    0       0           0                  4           696
3        8   4    23   1        1  1    1       1           0                 30           744
4        3   3   123   0        0  0    0       0           0                126           720
5        7   4     0   0        0  0    0       0           0                  7           744
6        0   1    15   0        0  0    0       0           0                 16           720
7        3   2     0   0        0  0    0       0           0                  3           744
8        5   4    53   3        2  3    1       2           0                 58           744
9        2   2    14   2        0  2    0       0           0                 18           720
10       0   0     8   0        0  0    1       0           0                  9           744
11       7   4    66   3        0  3    0       0           0                 77           720
12       3   1     0   0        0  0    0       0           0                  3           744
2013
       NO2  O3  PM10  Hr  RainDur  T  WVv  StrGlo  n_vehicles  Rows_with_any_NaN  Possible_max
Month
1        2   0     0   1        0  1    0       0           0                  3           744
2        3   1    11   2        0  2    0       0           0                 16           672
3        0   0     0   1        0  1    0       0           0                  1           744
4        0   0     0   2        0  2    0       0           0                  2           720
5        9   5     0   2        1  2    7       1           0                 18           744
6        5   2     5   0        0  0    0       0           0                 10           720
7        6   2     3   1        0  1    0       0           0                 10           744
8        2   1     0   1        0  1    0       0           0                  3           744
9        4   1    58   0        1  0    2       1           0                 63           720
10       5   3    85   1        0  1    0       0           0                 91           744
11       4   3    30   4        1  4    1       1           0                 37           720
12       9   6     0   1        0  1    0       0           0                 10           744
2014
       NO2  O3  PM10  Hr  RainDur   T  WVv  StrGlo  n_vehicles  Rows_with_any_NaN  Possible_max
Month
1        5   2     9  26        0  19    0       0           0                 38           744
2        0   0     0   0        0   0    0       0           0                  0           672
3        8   4    12   2        1   2    1       1           0                 19           744
4        3   2    26   1        0   1    0       0           0                 29           720
5        5   4     0  26        2  26    2       2           0                 30           744
6        3   2    18   1        0   1    0       0           0                 19           720
7        5   4     0   1        0   1    0       0           0                  6           744
8        6  54     5   3        2   3    2       2           0                 58           744
9        5   2    87   1        0   1    0       0           0                 92           720
10       3   3     1   1        1   1    1       1           0                  3           744
11       5   2     6  40        0   1    0       0           0                 51           720
12       5   3    49   1        0   1    0       0           0                 55           744
2015
       NO2  O3  PM10  Hr  RainDur  T  WVv  StrGlo  n_vehicles  Rows_with_any_NaN  Possible_max
Month
1        7   5     0   3        0  3    0       0           0                  9           744
2        3   2     0   0        0  0    0       0           0                  3           672
3        4   4    42   2        0  2    1       0           0                 49           744
4        4   3    71   0        0  0    0       0           0                 75           720
5        3   2   123   1       27  1   27      27           0                152           744
6        7   5   121   5        2  5    2       2           0                129           720
7        8   9     1   2        0  2    0       0           0                 14           744
8        2   1    28   0        0  0    0       0           0                 30           744
9        4   2    37   0        0  0    0       0           0                 41           720
10       6   3     0   0        0  0    0       0           0                  6           744
11       6   2     5   0        0  0    1       0           0                 12           720
12       9   6     3   3        3  3    3       3           0                  9           744
2016
       NO2  O3  PM10  Hr  RainDur   T  WVv  StrGlo  n_vehicles  Rows_with_any_NaN  Possible_max
Month
1        8   8     3   3        1   3    1       1           0                 12           744
2        4   3     0   0        0   0    0       0           0                  4           696
3        5   7     0   1        0   1    0       0           0                 11           744
4        2   1     0   0        0   0    0       0           0                  2           720
5        4   3    47   3        1   3    1       1           0                 52           744
6        1   3    46   1        0   1    0       0           0                 50           720
7        7   5    66   2        1   2    1       1           0                 73           744
8        2   2    41   1        0   1    1       0           0                 44           744
9        9   5    10   1        9   1   10       9           0                 21           720
10       2   1    15   0        0   0    0       0           0                 17           744
11       5   4     0   2        0   2    0       0           0                  8           720
12      13  12     9  11        9  11   10       9           0                 15           744
2017
       NO2  O3  PM10  Hr  RainDur  T  WVv  StrGlo  n_vehicles  Rows_with_any_NaN  Possible_max
Month
1        6   4    10   2        0  2    0       0           0                 16           744
2        3   2     4   0        0  1    0       0           0                  6           672
3        3   4     0   3        0  3    0       0           0                  5           744
4        3   2     2   1        0  1    0       0           0                  5           720
5        4   4     4   3        2  3    2       2           0                  7           744
6        4   1    17   2        2  2    2       2           0                 18           720
7        2   1     6   0        6  0    6       6           0                  8           744
8        2   1     2   0        0  0    0       0           0                  5           744
9        3   3    28   2        2  2    2       2           0                 28           720
10       7   5     2   2        2  2    3       2           0                  9           744
11       5   3     4   1        1  1    1       1           0                  6           720
12       2   2     5   1        1  1    1       1           0                  6           744
2018
       NO2  O3  PM10  Hr  RainDur  T  WVv  StrGlo  n_vehicles  Rows_with_any_NaN  Possible_max
Month
1        5   5     4   2        2  2    2       2           0                  6           744
2        2   2    77   1        1  1    1       1           0                 78           672
3        5   3     2   0        0  0    0       0           0                  5           744
4        5   2     1   1        2  1    2       2           0                  6           720
5        5   4     1   1        1  1    1       1           0                  5           744
6        3   2     7   1        1  1    1       1           0                  8           720
7        2  11     0   0        0  0    0       0           0                 13           744
8        0   0     0   0        0  0    0       0           0                  0           744
9        2   2     0   0        0  0    0       0           0                  3           720
10      15  12     2   2        2  2    3       2           0                 16           744
11       5  37     1   0        0  0    0       0           0                 39           720
12       2   1     2   0        0  0    0       0           0                  2           744
2019
       NO2  O3  PM10  Hr  RainDur  T  WVv  StrGlo  n_vehicles  Rows_with_any_NaN  Possible_max
Month
1        5   2     4   0        0  0    0       0           0                  9           744
2        2   2     1   1        1  1    1       1           0                  2           672
3        3   2     0   1        0  1    0       0           0                  4           744
4       11   7     6   4        3  4    3       3           0                 11           720
5        0   0     0   0        0  0    0       0           0                  0           744
6        4   1     0   0        0  0    0       0           0                  4           720
7        4   2     0   0        1  0    2       1           0                  7           744
8        3   5     3   1        1  1    1       1           0                  7           744
9        2   2     0  27        0  2    0       0           0                 27           720
10      14  11     8   8        8  8    8       8           0                 14           744
11       3   2     1   0        0  0    0       0           0                  4           720
12       5   3     2   0        0  0    0       0           0                  6           744
2020
       NO2  O3  PM10   Hr  RainDur    T  WVv  StrGlo  n_vehicles  Rows_with_any_NaN  Possible_max
Month
1        4   3    52    0        0    0    0       0           0                 56           744
2        5   3    10    0        0    0    0       0           0                 13           696
3       27  24    22   22       22   22   20      22           0                 27           744
4        6   4     3    2        2    2    0       2           0                  7           720
5        8   6     2    2        2    2    0       2           0                  8           744
6        6  26     3    1        1    1    0       1           0                 29           720
7        9   5     1    1        1    1    0       1           0                  9           744
8        5   2    14    1        1    1    0       1           0                 18           744
9        6   5     1    0        0    0    0       0           0                  7           720
10       9   5     0    0        0    0    0       0           0                  9           744
11       3   3     0  124        0  124    0       0           0                127           720
12       5   4     1   13        0   13    0       0           0                 18           744
2021
       NO2  O3  PM10   Hr  RainDur    T  WVv  StrGlo  n_vehicles  Rows_with_any_NaN  Possible_max
Month
1        4   2     0    0        0    0    0       0           0                  4           744
2        4   3     1    0        0    0    0       0           0                  5           672
3        7   8   102    0        0    0    0       0           0                113           744
4        3   1     0  127        0  127    0       0           0                127           720
5        2   1     0    0        2    0    0       2           0                  4           744
6        6   4     0    0        0    0    0       0           0                  6           720
7        5  46     2    0        0    0    0       0           0                 47           744
8        3   1     0    0        0    0    0       0           0                  3           744
9        2   2     0    0        0    0    0       0           0                  3           720
10       2   2     0    0        0    0    0       0           0                  2           744
11       4   2     1    1        1    1    0       1           0                  4           720
12       7   1     2    0        0    0    0       0           0                  7           744
2022
       NO2  O3  PM10  Hr  RainDur  T  WVv  StrGlo  n_vehicles  Rows_with_any_NaN  Possible_max
Month
1        5   4     0   0        0  0    0       0           0                  6           744
2        4  31     0   0        0  0    0       0           0                 32           672
3        3   3     0   0        0  0    0       0           0                  4           744
4        5   3     0   0        0  0    0       0           0                  5           720
5        0   0     1   0        0  0    0       0           0                  1           744
6        6   4    35   1        1  1    0       1           0                 41           720
7        3   2   344   0        0  0    0       0           0                344           744
8        4   1     0   0        0  0    0       0           0                  4           744
9        5   4     0   0        0  0    0       0           0                  6           720
10       4   3     5   1        1  1    0       1           0                  6           744
11       4   2     3   1        0  1    0       0           0                  6           720
12       2   2   158   0        0  0    0       0           0                160           744
2023
       NO2  O3  PM10  Hr  RainDur  T  WVv  StrGlo  n_vehicles  Rows_with_any_NaN  Possible_max
Month
1        5   3     1   1        1  1    0       1           0                  5           744
2        9   6     4   4        2  4    0       2           0                 11           672
3        4  22     0   0        0  0    0       0           0                 22           744
4        3   2     0   0        0  0    3       0           0                  6           720
5        8   8     3   0        0  0    0       0           0                  9           744
6        5   4     0   0        1  0    0       1           0                  6           720
7        2   1     2   0        0  0    0       0           0                  2           744
8        5   1     0   0        0  0    0       0           0                  5           744
9        3   2     0   0        0  0    0       0           0                  4           720
10       2   1     0   0        0  0    0       0           0                  2           744
11       4   3     0   0        0  0    0       0           0                  4           720
12       2   2     0   0        0  0    0       0           0                  2           744
2024
       NO2  O3  PM10  Hr  RainDur  T  WVv  StrGlo  n_vehicles  Rows_with_any_NaN  Possible_max
Month
1        6   5     2   0        0  0    0       0           0                  6           744
2       13  13     9   8        8  8    7       8           0                 14           696
3       10   9     8   9        8  9    8       8           0                 10           744
4        5   1     1   1        1  1    0       1           0                  5           720
5        7   4     3   3        3  3    1       6           0                 10           744
6        1   1     0   0        0  0    0       1           0                  2           720
7        5   1     0   0        0  0    0       1           0                  6           744
8        3   2     0   1        0  1    0       0           0                  5           744
9        3   2     0   0        0  0    0       0           0                  3           720
10       4   2     0   1        0  1    0       0           0                  6           744
11       5   7     1   3        3  3    2       3           0                  8           720
12       6   4     0   1        0  1    0       0           0                  7           744
2025
       NO2  O3  PM10  Hr  RainDur  T  WVv  StrGlo  n_vehicles  Rows_with_any_NaN  Possible_max
Month
1        1   1     0   1        0  1    0       0           0                  2           744
2        3   5     0   0        0  0    0       0           0                  6           672
3        2   2     2   0        0  0    0       0           0                  4           744
4        3   2     0   1        0  1    0       0           0                  4           720
5        3   3     0   1        0  1    0       0           0                  5           744
6        3   0     0   1        0  1    0       0           0                  4           720
7        3   4     3   1        0  1    0       0           0                  8           744
8       44   1     0   1        0  1    0       0           0                 44           744
9       77   1     0   1        0  1    0       0           0                 78           720
10       6   2     0   2        0  2    0       0           0                  8           744
11       0   0     0   0        0  0    0       0           0                  0           720
12       6   4     1   3        1  3    1       1           0                  8           744