In [13]:
import pandas as pd

In [14]:
# Import traffic data
df_traffic = pd.read_csv("data/traffic_data_17_24.csv")
df_traffic.head()

,ZSName,MessungDatZeit,AnzFahrzeuge,Year,Datetime,pollutant_station
0,Rosengartenstrasse (Nordstrasse),2017-01-01T00:00:00,611.0,2017,2017-01-01 00:00:00,Zch_Rosengartenstrasse
1,Rosengartenstrasse (Nordstrasse),2017-01-01T01:00:00,1278.0,2017,2017-01-01 01:00:00,Zch_Rosengartenstrasse
2,Rosengartenstrasse (Nordstrasse),2017-01-01T02:00:00,950.0,2017,2017-01-01 02:00:00,Zch_Rosengartenstrasse
3,Rosengartenstrasse (Nordstrasse),2017-01-01T03:00:00,716.0,2017,2017-01-01 03:00:00,Zch_Rosengartenstrasse
4,Rosengartenstrasse (Nordstrasse),2017-01-01T04:00:00,638.0,2017,2017-01-01 04:00:00,Zch_Rosengartenstrasse

In [15]:
# Exclude Heubeeribüel
df_test = df_traffic[df_traffic["pollutant_station"] != "Zch_Heubeeribüel"]

# Count occurrences of each (Standort, Datetime)
counts = (
    df_test.groupby(['pollutant_station', 'Datetime']).size().rename('n').reset_index()
)

# Identify any groups that do NOT have exactly 2 rows
problematic = counts[counts['n']!=2]
problematic

              pollutant_station             Datetime  n
7225     Zch_Rosengartenstrasse  2017-10-29 02:00:00  4
15960    Zch_Rosengartenstrasse  2018-10-28 02:00:00  4
24695    Zch_Rosengartenstrasse  2019-10-27 02:00:00  4
33430    Zch_Rosengartenstrasse  2020-10-25 02:00:00  4
42333    Zch_Rosengartenstrasse  2021-10-31 02:00:00  4
51068    Zch_Rosengartenstrasse  2022-10-30 02:00:00  4
59803    Zch_Rosengartenstrasse  2023-10-29 02:00:00  4
68538    Zch_Rosengartenstrasse  2024-10-27 02:00:00  4
77345       Zch_Schimmelstrasse  2017-10-29 02:00:00  4
86080       Zch_Schimmelstrasse  2018-10-28 02:00:00  4
94815       Zch_Schimmelstrasse  2019-10-27 02:00:00  4
103550      Zch_Schimmelstrasse  2020-10-25 02:00:00  4
112453      Zch_Schimmelstrasse  2021-10-31 02:00:00  4
121188      Zch_Schimmelstrasse  2022-10-30 02:00:00  4
129923      Zch_Schimmelstrasse  2023-10-29 02:00:00  4
138658      Zch_Schimmelstrasse  2024-10-27 02:00:00  4
147465  Zch_Stampfenbachstrasse  2017-10-29 02:00:00  4
156200  Zch_Stampfenbachstrasse  2018-10-28 02:00:00  4
164935  Zch_Stampfenbachstrasse  2019-10-27 02:00:00  4
173670  Zch_Stampfenbachstrasse  2020-10-25 02:00:00  4
182573  Zch_Stampfenbachstrasse  2021-10-31 02:00:00  4
191308  Zch_Stampfenbachstrasse  2022-10-30 02:00:00  4
200043  Zch_Stampfenbachstrasse  2023-10-29 02:00:00  4
208778  Zch_Stampfenbachstrasse  2024-10-27 02:00:00  4