# Libraries

In [2]:
import pandas as pd

# Data

## Air Pollution Data

In [3]:
def read_files(file_paths: list, drop_columns: list):
    dfs = [
        pd.read_csv(file).assign(year=int(file[-8:-4])).drop(columns=drop_columns)
        for file in file_paths
    ]

    df = pd.concat(dfs, ignore_index=True)

    return df

In [ ]:
filenames_pollutants = ["data/ugz_ogd_air_d1_2023.csv", "data/ugz_ogd_air_d1_2024.csv"]

#df_pollutants = read_files(file_paths=filenames_pollutants, drop_columns=["Status", "Intervall"])

# Creating pandas dataframe instead of using the function read_files
df_pollutants = pd.concat(
    [pd.read_csv(f).drop(columns=["Status", "Intervall"]) for f in filenames_pollutants],
    ignore_index=True
)

df_pollutants

,Datum,Standort,Parameter,Einheit,Wert
0,2023-01-01T00:00+0100,Zch_Stampfenbachstrasse,SO2,µg/m3,1.51
1,2023-01-01T00:00+0100,Zch_Stampfenbachstrasse,CO,mg/m3,0.35
2,2023-01-01T00:00+0100,Zch_Stampfenbachstrasse,NOx,ppb,27.13
3,2023-01-01T00:00+0100,Zch_Stampfenbachstrasse,NO,µg/m3,16.57
4,2023-01-01T00:00+0100,Zch_Stampfenbachstrasse,NO2,µg/m3,26.47
...,...,...,...,...,...
25581,2024-12-31T00:00+0100,Zch_Heubeeribüel,O3,µg/m3,13.42
25582,2024-12-31T00:00+0100,Zch_Heubeeribüel,PM10,µg/m3,13.75
25583,2024-12-31T00:00+0100,Zch_Heubeeribüel,PM2.5,µg/m3,13.36
25584,2024-12-31T00:00+0100,Zch_Heubeeribüel,O3_max_h1,µg/m3,27.65
25585,2024-12-31T00:00+0100,Zch_Heubeeribüel,O3_nb_h1>120,1,0.00

In [35]:

# Display df_pollutants info and missing values
print("df_pollutants shape:", df_pollutants.shape)
print("\nMissing values per column:")
print(df_pollutants.isnull().sum())
print("\nData types:")
print(df_pollutants.dtypes)

df_pollutants shape: (25586, 5)

Missing values per column:
Datum          0
Standort       0
Parameter      0
Einheit        0
Wert         858
dtype: int64

Data types:
Datum         object
Standort      object
Parameter     object
Einheit       object
Wert         float64
dtype: object

In [22]:
param_units_pollutants = (
    df_pollutants[["Parameter", "Einheit"]]
    .drop_duplicates()
    .reset_index(drop=True)
)

param_units_pollutants

       Parameter Einheit
0            SO2   µg/m3
1             CO   mg/m3
2            NOx     ppb
3             NO   µg/m3
4            NO2   µg/m3
5             O3   µg/m3
6           PM10   µg/m3
7          PM2.5   µg/m3
8      O3_max_h1   µg/m3
9   O3_nb_h1>120       1
10            PN   1/cm3

In [63]:
# Pivot with split date and time columns

# 1) Parse 'Datum' as timezone-aware datetime
# Pandas can parse 'YYYY-MM-DDTHH:MM+0100' directly.
df_pollutants["Datum"] = pd.to_datetime(df_pollutants["Datum"], errors="coerce")

# 2) Create date and time columns
df_pollutants["Datum_date"] = df_pollutants["Datum"].dt.date      # dtype: object (date objects)
df_pollutants["Datum_time"] = df_pollutants["Datum"].dt.time      # dtype: object (time objects)

# Optional: if you prefer pure pandas dtypes (no Python date/time objects),
# you can keep them as strings or as datetime64:
# df_pollutants["Datum_date"] = df_pollutants["Datum"].dt.strftime("%Y-%m-%d")
# df_pollutants["Datum_time"] = df_pollutants["Datum"].dt.strftime("%H:%M:%S%z")

# 3) Now pivot using the original 'Datum' or the split columns as needed
df_pollutants_pivot = df_pollutants.pivot(
    #index=["Datum", "Standort"], 
    index = ['Datum_date','Datum_time','Standort'], # you can also use ['Datum_date','Datum_time','Standort']
    columns="Parameter",
    values="Wert"
)

# 4) Drop unwanted columns (handle the HTML entity if present)
cols_to_drop = ["CO", "O3_max_h1", "O3_nb_h1>120", "SO2", "PN"] # in these two there are also many NAs:, "PM10", "PM2.5"]
df_pollutants_pivot = df_pollutants_pivot.drop(
    columns=[c for c in cols_to_drop if c in df_pollutants_pivot.columns],
    errors="ignore"
)

df_pollutants_pivot

Parameter                                         NO    NO2    NOx     O3  \
Datum_date Datum_time Standort
2023-01-01 00:00:00   Zch_Heubeeribüel          0.71   4.27   2.80  51.47
                      Zch_Rosengartenstrasse   34.90  36.30  46.96  18.24
                      Zch_Schimmelstrasse      16.44  25.13  26.32  23.48
                      Zch_Stampfenbachstrasse  16.57  26.47  27.13  20.00
2023-01-02 00:00:00   Zch_Heubeeribüel          0.66   4.66   2.96  57.65
...                                              ...    ...    ...    ...
2024-12-30 00:00:00   Zch_Stampfenbachstrasse   9.24  34.43  25.41   6.90
2024-12-31 00:00:00   Zch_Heubeeribüel          5.07  28.53  18.98  13.42
                      Zch_Rosengartenstrasse   21.20  40.10  37.96   5.97
                      Zch_Schimmelstrasse      18.14  38.21  34.53   7.71
                      Zch_Stampfenbachstrasse   8.81  35.57  25.66   7.55

Parameter                                       PM10  PM2.5
Datum_date Datum_time Standort
2023-01-01 00:00:00   Zch_Heubeeribüel           NaN    NaN
                      Zch_Rosengartenstrasse   16.22  14.55
                      Zch_Schimmelstrasse      14.78  13.04
                      Zch_Stampfenbachstrasse  22.99  17.52
2023-01-02 00:00:00   Zch_Heubeeribüel           NaN    NaN
...                                              ...    ...
2024-12-30 00:00:00   Zch_Stampfenbachstrasse  16.72  14.94
2024-12-31 00:00:00   Zch_Heubeeribüel         13.75  13.36
                      Zch_Rosengartenstrasse   21.54  21.01
                      Zch_Schimmelstrasse      18.54  18.57
                      Zch_Stampfenbachstrasse  19.18  17.44

[2924 rows x 6 columns]

In [ ]:
# Pivot of Selina
df_pollutants_pivot = df_pollutants.pivot(index=["Datum", "Standort"], columns="Parameter", values="Wert")
df_pollutants_pivot = df_pollutants_pivot.drop(columns=["CO", "O3_max_h1", "O3_nb_h1>120", "SO2", "PN"])

df_pollutants_pivot
#df_pollutants_pivot.head()
#df_pollutants_pivot.tail()

Parameter                                         NO    NO2    NOx     O3  \
Datum                 Standort
2023-01-01T00:00+0100 Zch_Heubeeribüel          0.71   4.27   2.80  51.47
                      Zch_Rosengartenstrasse   34.90  36.30  46.96  18.24
                      Zch_Schimmelstrasse      16.44  25.13  26.32  23.48
                      Zch_Stampfenbachstrasse  16.57  26.47  27.13  20.00
2023-01-02T00:00+0100 Zch_Heubeeribüel          0.66   4.66   2.96  57.65
...                                              ...    ...    ...    ...
2024-12-30T00:00+0100 Zch_Stampfenbachstrasse   9.24  34.43  25.41   6.90
2024-12-31T00:00+0100 Zch_Heubeeribüel          5.07  28.53  18.98  13.42
                      Zch_Rosengartenstrasse   21.20  40.10  37.96   5.97
                      Zch_Schimmelstrasse      18.14  38.21  34.53   7.71
                      Zch_Stampfenbachstrasse   8.81  35.57  25.66   7.55

Parameter                                       PM10  PM2.5
Datum                 Standort
2023-01-01T00:00+0100 Zch_Heubeeribüel           NaN    NaN
                      Zch_Rosengartenstrasse   16.22  14.55
                      Zch_Schimmelstrasse      14.78  13.04
                      Zch_Stampfenbachstrasse  22.99  17.52
2023-01-02T00:00+0100 Zch_Heubeeribüel           NaN    NaN
...                                              ...    ...
2024-12-30T00:00+0100 Zch_Stampfenbachstrasse  16.72  14.94
2024-12-31T00:00+0100 Zch_Heubeeribüel         13.75  13.36
                      Zch_Rosengartenstrasse   21.54  21.01
                      Zch_Schimmelstrasse      18.54  18.57
                      Zch_Stampfenbachstrasse  19.18  17.44

[2924 rows x 6 columns]

In [64]:
# Display df_pollutants info and missing values
print("df_pollutants shape:", df_pollutants_pivot.shape)
print("\nMissing values per column:")
print(df_pollutants_pivot.isnull().sum())
print("\nData types:")
print(df_pollutants_pivot.dtypes)

df_pollutants shape: (2924, 6)

Missing values per column:
Parameter
NO        78
NO2       78
NOx       78
O3        67
PM10     493
PM2.5    493
dtype: int64

Data types:
Parameter
NO       float64
NO2      float64
NOx      float64
O3       float64
PM10     float64
PM2.5    float64
dtype: object

In [ ]:
import pandas as pd

# 1) Boolean mask: any pollutant missing in a row (row = one index combination)
row_has_na = df_pollutants_pivot.isna().any(axis=1)

# 2) Build a long DataFrame of NA cells → includes the pollutant column
na_long = (
    df_pollutants_pivot
      .isna()
      .stack()                     # adds a "level_3" (pollutant) index level
      .rename("is_na")
      .reset_index()
)

# 3) Keep only the missing entries
na_long = na_long[na_long["is_na"]].drop(columns="is_na")

# 4) Rename the stacked column to "Parameter" (pollutant)
# The name of the stacked column depends on your frame; it's often "level_3" or similar.
stacked_col = [c for c in na_long.columns if c not in ["Datum_date", "Datum_time", "Standort"]][0]
na_long = na_long.rename(columns={stacked_col: "Parameter"})

# 5) Sort for readability
na_long = na_long.sort_values(["Datum_date", "Datum_time", "Standort", "Parameter"]).reset_index(drop=True)

# Now you have the four columns you want:
# Columns: Datum_date, Datum_time, Standort, Parameter
print(na_long.head(10))

# 6) Pretty print grouped by timestamp → list stations together with pollutants
from collections import defaultdict

by_dt = defaultdict(list)
for _, r in na_long.iterrows():
    key = (str(r["Datum_date"]), str(r["Datum_time"]))
    by_dt[key].append((str(r["Standort"]), str(r["Parameter"])))

print(f"{len(na_long)} missing cells (grouped):")
for (d, t) in sorted(by_dt.keys()):
    # aggregate per location: collect pollutants per Standort
    loc_to_poll = defaultdict(set)
    for loc, param in by_dt[(d, t)]:
        loc_to_poll[loc].add(param)
    parts = [f"{loc}: {', '.join(sorted(params))}" for loc, params in sorted(loc_to_poll.items())]
    print(f"{d} {t} → " + " | ".join(parts))

   Datum_date Datum_time          Standort Parameter
0  2023-01-01   00:00:00  Zch_Heubeeribüel      PM10
1  2023-01-01   00:00:00  Zch_Heubeeribüel     PM2.5
2  2023-01-02   00:00:00  Zch_Heubeeribüel      PM10
3  2023-01-02   00:00:00  Zch_Heubeeribüel     PM2.5
4  2023-01-03   00:00:00  Zch_Heubeeribüel      PM10
5  2023-01-03   00:00:00  Zch_Heubeeribüel     PM2.5
6  2023-01-04   00:00:00  Zch_Heubeeribüel      PM10
7  2023-01-04   00:00:00  Zch_Heubeeribüel     PM2.5
8  2023-01-05   00:00:00  Zch_Heubeeribüel      PM10
9  2023-01-05   00:00:00  Zch_Heubeeribüel     PM2.5
1287 missing cells (grouped):
2023-01-01 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-01-02 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-01-03 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-01-04 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-01-05 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-01-06 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-01-07 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-01-08 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-01-09 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-01-10 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-01-11 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-01-12 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-01-13 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-01-14 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-01-15 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-01-16 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-01-17 00:00:00 → Zch_Heubeeribüel: NO, NO2, NOx, PM10, PM2.5
2023-01-18 00:00:00 → Zch_Heubeeribüel: NO, NO2, NOx, PM10, PM2.5
2023-01-19 00:00:00 → Zch_Heubeeribüel: NO, NO2, NOx, PM10, PM2.5
2023-01-20 00:00:00 → Zch_Heubeeribüel: NO, NO2, NOx, PM10, PM2.5
2023-01-21 00:00:00 → Zch_Heubeeribüel: NO, NO2, NOx, PM10, PM2.5
2023-01-22 00:00:00 → Zch_Heubeeribüel: NO, NO2, NOx, PM10, PM2.5
2023-01-23 00:00:00 → Zch_Heubeeribüel: NO, NO2, NOx, PM10, PM2.5
2023-01-24 00:00:00 → Zch_Heubeeribüel: NO, NO2, NOx, PM10, PM2.5
2023-01-25 00:00:00 → Zch_Heubeeribüel: NO, NO2, NOx, PM10, PM2.5
2023-01-26 00:00:00 → Zch_Heubeeribüel: NO, NO2, NOx, PM10, PM2.5
2023-01-27 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-01-28 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-01-29 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-01-30 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-01-31 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-02-01 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-02-02 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-02-03 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-02-04 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-02-05 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-02-06 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-02-07 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-02-08 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-02-09 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-02-10 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Schimmelstrasse: NO, NO2, NOx, O3, PM10, PM2.5
2023-02-11 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Schimmelstrasse: NO, NO2, NOx, O3, PM10, PM2.5
2023-02-12 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Schimmelstrasse: NO, NO2, NOx, O3, PM10, PM2.5
2023-02-13 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5 | Zch_Schimmelstrasse: NO, NO2, NOx, O3, PM10, PM2.5
2023-02-14 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-02-15 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-02-16 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-02-17 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-02-18 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-02-19 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-02-20 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-02-21 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-02-22 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-02-23 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-02-24 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-02-25 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-02-26 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-02-27 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-02-28 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-03-01 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-03-02 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-03-03 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-03-04 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-03-05 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-03-06 00:00:00 → Zch_Heubeeribüel: O3, PM10, PM2.5
2023-03-07 00:00:00 → Zch_Heubeeribüel: O3, PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-03-08 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-03-09 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-03-10 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Stampfenbachstrasse: O3
2023-03-11 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Stampfenbachstrasse: O3
2023-03-12 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-03-13 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-03-14 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-03-15 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-03-16 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-03-17 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-03-18 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-03-19 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-03-20 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-03-21 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-03-22 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-03-23 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-03-24 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-03-25 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-03-26 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-03-27 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-03-28 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-03-29 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-03-30 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-03-31 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-04-01 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-04-02 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-04-03 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-04-04 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-04-05 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-04-06 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-04-07 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-04-08 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-04-09 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-04-10 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-04-11 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-04-12 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-04-13 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-04-14 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-04-15 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-04-16 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-04-17 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-04-18 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-04-19 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-04-20 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-04-21 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-04-22 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-04-23 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-04-24 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-04-25 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-04-26 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-04-27 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-04-28 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-04-29 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-04-30 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-05-01 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-05-02 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-05-03 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-05-04 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-05-05 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-05-06 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-05-07 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-05-08 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-05-09 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-05-10 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-05-11 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-05-12 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-05-13 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-05-14 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-05-15 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-05-16 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-05-17 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-05-18 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-05-19 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-05-20 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-05-21 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-05-22 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-05-23 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-05-24 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-05-25 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-05-26 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-05-27 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-05-28 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-05-29 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-05-30 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-05-31 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-06-01 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-06-02 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-06-03 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-06-04 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-06-05 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-06-06 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-06-07 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-06-08 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-06-09 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-06-10 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-06-11 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-06-12 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-06-13 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-06-14 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-06-15 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-06-16 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-06-17 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-06-18 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-06-19 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-06-20 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-06-21 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-06-22 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-06-23 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-06-24 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-06-25 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-06-26 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5 | Zch_Schimmelstrasse: NO, NO2, NOx, O3, PM10, PM2.5
2023-06-27 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Schimmelstrasse: NO, NO2, NOx, O3, PM10, PM2.5
2023-06-28 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5 | Zch_Schimmelstrasse: NO, NO2, NOx, O3, PM10, PM2.5
2023-06-29 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5 | Zch_Schimmelstrasse: NO, NO2, NOx, O3, PM10, PM2.5
2023-06-30 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5 | Zch_Schimmelstrasse: NO, NO2, NOx, O3, PM10, PM2.5
2023-07-01 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-07-02 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-07-03 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-07-04 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-07-05 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-07-06 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-07-07 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-07-08 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-07-09 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-07-10 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-07-11 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-07-12 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-07-13 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-07-14 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-07-15 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-07-16 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-07-17 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-07-18 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-07-19 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-07-20 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-07-21 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-07-22 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-07-23 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-07-24 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-07-25 00:00:00 → Zch_Heubeeribüel: NO, NO2, NOx, O3, PM10, PM2.5
2023-07-26 00:00:00 → Zch_Heubeeribüel: NO, NO2, NOx, O3, PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-07-27 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-07-28 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-07-29 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-07-30 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-07-31 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-08-01 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-08-02 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-08-03 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-08-04 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-08-05 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-08-06 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-08-07 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-08-08 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-08-09 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-08-10 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-08-11 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-08-12 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-08-13 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-08-14 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-08-15 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-08-16 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-08-17 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-08-18 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-08-19 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Schimmelstrasse: NO, NO2, NOx, O3, PM10, PM2.5
2023-08-20 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-08-21 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-08-22 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-08-23 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-08-24 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-08-25 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-08-26 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-08-27 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-08-28 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-08-29 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-08-30 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-08-31 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-09-01 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-09-02 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-09-03 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-09-04 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-09-05 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: O3, PM10, PM2.5
2023-09-06 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-09-07 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-09-08 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-09-09 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-09-10 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-09-11 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-09-12 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-09-13 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-09-14 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-09-15 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-09-16 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-09-17 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-09-18 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-09-19 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-09-20 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-09-21 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-09-22 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-09-23 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-09-24 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-09-25 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-09-26 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-09-27 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-09-28 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-09-29 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-09-30 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-10-01 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-10-02 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-10-03 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-10-04 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-10-05 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: O3
2023-10-06 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: O3
2023-10-07 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-10-08 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-10-09 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-10-10 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-10-11 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-10-12 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-10-13 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-10-14 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-10-15 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-10-16 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-10-17 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-10-18 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: O3, PM10, PM2.5
2023-10-19 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: NO, NO2, NOx, O3, PM10, PM2.5
2023-10-20 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-10-21 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-10-22 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-10-23 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-10-24 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Schimmelstrasse: NO, NO2, NOx, O3, PM10, PM2.5
2023-10-25 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5 | Zch_Schimmelstrasse: NO, NO2, NOx, O3, PM10, PM2.5
2023-10-26 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5
2023-10-27 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-10-28 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-10-29 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-10-30 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5
2023-10-31 00:00:00 → Zch_Heubeeribüel: PM10, PM2.5 | Zch_Rosengartenstrasse: PM10, PM2.5

## Traffic Data

In [39]:
df_traffic = pd.read_csv("data/traffic_data_2023_2024.csv")
df_traffic.head()

,ZSName,MessungDatZeit,AnzFahrzeuge,year,pollutant_station
0,Rosengartenstrasse (Nordstrasse),2023-01-01T00:00:00,688.0,2023,Zch_Rosengartenstrasse
1,Rosengartenstrasse (Nordstrasse),2023-01-01T01:00:00,1370.0,2023,Zch_Rosengartenstrasse
2,Rosengartenstrasse (Nordstrasse),2023-01-01T02:00:00,1041.0,2023,Zch_Rosengartenstrasse
3,Rosengartenstrasse (Nordstrasse),2023-01-01T03:00:00,661.0,2023,Zch_Rosengartenstrasse
4,Rosengartenstrasse (Nordstrasse),2023-01-01T04:00:00,528.0,2023,Zch_Rosengartenstrasse

In [86]:
# 1) Parse MessungDatZeit safely into datetime
df_traffic["MessungDatZeit"] = pd.to_datetime(
    df_traffic["MessungDatZeit"], errors="coerce"  # handles bad rows as NaT
)

# 2) If your timestamps have timezone offsets and you want to remove tz info, uncomment:
# df_traffic["MessungDatZeit"] = df_traffic["MessungDatZeit"].dt.tz_localize(None)

# 3) Create separate columns for date & time
df_traffic["Messung_date"] = df_traffic["MessungDatZeit"].dt.date     # dtype: object (datetime.date)
df_traffic["Messung_time"] = df_traffic["MessungDatZeit"].dt.time     # dtype: object (datetime.time)

# rename pollutant_station to Standort to match df_pollutants
df_traffic = df_traffic.rename(columns={"pollutant_station": "Standort"})

# delete ZSName column
df_traffic = df_traffic.drop(columns=["ZSName"], errors="ignore")

# reorder columns
column_order = ["year", "Messung_date", "Messung_time", "MessungDatZeit", "Standort", "AnzFahrzeuge"]
df_traffic = df_traffic[column_order]

# (Optional) If you prefer **string** columns (sometimes easier to export/sort):
# df_traffic["messung_date"] = df_traffic["MessungDatZeit"].dt.strftime("%Y-%m-%d")
# df_traffic["messung_time"] = df_traffic["MessungDatZeit"].dt.strftime("%H:%M:%S")

df_traffic

,year,Messung_date,Messung_time,MessungDatZeit,Standort,AnzFahrzeuge
0,2023,2023-01-01,00:00:00,2023-01-01 00:00:00,Zch_Rosengartenstrasse,688.0
1,2023,2023-01-01,01:00:00,2023-01-01 01:00:00,Zch_Rosengartenstrasse,1370.0
2,2023,2023-01-01,02:00:00,2023-01-01 02:00:00,Zch_Rosengartenstrasse,1041.0
3,2023,2023-01-01,03:00:00,2023-01-01 03:00:00,Zch_Rosengartenstrasse,661.0
4,2023,2023-01-01,04:00:00,2023-01-01 04:00:00,Zch_Rosengartenstrasse,528.0
...,...,...,...,...,...,...
119947,2024,2024-12-31,19:00:00,2024-12-31 19:00:00,Zch_Heubeeribüel,14.0
119948,2024,2024-12-31,20:00:00,2024-12-31 20:00:00,Zch_Heubeeribüel,14.0
119949,2024,2024-12-31,21:00:00,2024-12-31 21:00:00,Zch_Heubeeribüel,15.0
119950,2024,2024-12-31,22:00:00,2024-12-31 22:00:00,Zch_Heubeeribüel,33.0
119951,2024,2024-12-31,23:00:00,2024-12-31 23:00:00,Zch_Heubeeribüel,29.0

In [82]:
# Display df_traffic info and missing values
print("df_traffic shape:", df_traffic.shape)
print("\nMissing values per column:")
print(df_traffic.isnull().sum())
print("\nData types:")
print(df_traffic.dtypes)

df_traffic shape: (119952, 6)

Missing values per column:
year                 0
messung_date         0
messung_time         0
MessungDatZeit       0
Standort             0
AnzFahrzeuge      1010
dtype: int64

Data types:
year                       int64
messung_date              object
messung_time              object
MessungDatZeit    datetime64[ns]
Standort                  object
AnzFahrzeuge             float64
dtype: object

In [ ]:
from collections import defaultdict

# Build your triplets
triplets = (
    df_traffic.loc[missing_mask, ["MessungDatZeit", "Standort"]]
      .dropna(subset=["MessungDatZeit"])
      .assign(
          date_str=lambda x: x["MessungDatZeit"].dt.strftime("%Y-%m-%d"),
          time_str=lambda x: x["MessungDatZeit"].dt.strftime("%H:%M:%S")
      )
      [["date_str", "time_str", "Standort"]]
      .values
      .tolist()
)

# 2) Sort by date, then time, then location
triplets.sort(key=lambda t: (t[0], t[1], t[2]))

# 3) Group locations per (date, time)
by_dt = defaultdict(list)
for date_str, time_str, loc in triplets:
    by_dt[(date_str, time_str)].append(loc)

# 4) Print in order (date, time), with locations joined
print(f"{len(triplets)} rows with missing 'AnzFahrzeuge' (grouped):")
for (date_str, time_str) in sorted(by_dt.keys()):
    locs = ", ".join(sorted(set(by_dt[(date_str, time_str)])))  # unique + sorted
    print(f"{date_str} {time_str} → {locs}")

1010 rows with missing 'AnzFahrzeuge' (grouped):
2023-02-13 22:00:00 → Zch_Stampfenbachstrasse
2023-02-13 23:00:00 → Zch_Stampfenbachstrasse
2023-02-16 21:00:00 → Zch_Stampfenbachstrasse
2023-02-16 22:00:00 → Zch_Stampfenbachstrasse
2023-03-13 21:00:00 → Zch_Stampfenbachstrasse
2023-03-13 22:00:00 → Zch_Stampfenbachstrasse
2023-03-13 23:00:00 → Zch_Stampfenbachstrasse
2023-03-14 00:00:00 → Zch_Stampfenbachstrasse
2023-03-22 10:00:00 → Zch_Rosengartenstrasse
2023-03-22 11:00:00 → Zch_Rosengartenstrasse
2023-05-05 17:00:00 → Zch_Rosengartenstrasse
2023-05-05 18:00:00 → Zch_Rosengartenstrasse
2023-05-05 19:00:00 → Zch_Rosengartenstrasse
2023-05-05 20:00:00 → Zch_Rosengartenstrasse
2023-12-13 13:00:00 → Zch_Schimmelstrasse
2023-12-13 14:00:00 → Zch_Schimmelstrasse
2024-01-08 00:00:00 → Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-01-08 01:00:00 → Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-01-08 02:00:00 → Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-01-08 03:00:00 → Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-01-08 04:00:00 → Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-01-08 05:00:00 → Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-01-08 06:00:00 → Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-01-08 07:00:00 → Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-01-08 08:00:00 → Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-01-08 09:00:00 → Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-01-08 10:00:00 → Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-01-08 11:00:00 → Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-01-08 12:00:00 → Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-01-08 13:00:00 → Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-01-08 14:00:00 → Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-02-03 14:00:00 → Zch_Stampfenbachstrasse
2024-02-03 15:00:00 → Zch_Stampfenbachstrasse
2024-02-03 16:00:00 → Zch_Stampfenbachstrasse
2024-02-03 17:00:00 → Zch_Stampfenbachstrasse
2024-02-03 18:00:00 → Zch_Stampfenbachstrasse
2024-02-03 19:00:00 → Zch_Stampfenbachstrasse
2024-02-03 20:00:00 → Zch_Stampfenbachstrasse
2024-02-03 21:00:00 → Zch_Stampfenbachstrasse
2024-02-03 22:00:00 → Zch_Stampfenbachstrasse
2024-02-03 23:00:00 → Zch_Stampfenbachstrasse
2024-02-04 00:00:00 → Zch_Stampfenbachstrasse
2024-02-04 01:00:00 → Zch_Stampfenbachstrasse
2024-02-04 02:00:00 → Zch_Stampfenbachstrasse
2024-02-04 03:00:00 → Zch_Stampfenbachstrasse
2024-02-04 04:00:00 → Zch_Stampfenbachstrasse
2024-02-04 05:00:00 → Zch_Stampfenbachstrasse
2024-02-04 06:00:00 → Zch_Stampfenbachstrasse
2024-02-04 07:00:00 → Zch_Stampfenbachstrasse
2024-02-04 08:00:00 → Zch_Stampfenbachstrasse
2024-02-04 09:00:00 → Zch_Stampfenbachstrasse
2024-02-04 10:00:00 → Zch_Stampfenbachstrasse
2024-02-04 11:00:00 → Zch_Stampfenbachstrasse
2024-02-04 12:00:00 → Zch_Stampfenbachstrasse
2024-02-04 13:00:00 → Zch_Stampfenbachstrasse
2024-02-04 14:00:00 → Zch_Stampfenbachstrasse
2024-02-04 15:00:00 → Zch_Stampfenbachstrasse
2024-02-04 16:00:00 → Zch_Stampfenbachstrasse
2024-02-04 17:00:00 → Zch_Stampfenbachstrasse
2024-02-04 18:00:00 → Zch_Stampfenbachstrasse
2024-02-04 19:00:00 → Zch_Stampfenbachstrasse
2024-02-04 20:00:00 → Zch_Stampfenbachstrasse
2024-02-04 21:00:00 → Zch_Stampfenbachstrasse
2024-02-04 22:00:00 → Zch_Stampfenbachstrasse
2024-02-04 23:00:00 → Zch_Stampfenbachstrasse
2024-02-05 00:00:00 → Zch_Stampfenbachstrasse
2024-02-05 01:00:00 → Zch_Stampfenbachstrasse
2024-02-05 02:00:00 → Zch_Stampfenbachstrasse
2024-02-05 03:00:00 → Zch_Stampfenbachstrasse
2024-02-05 04:00:00 → Zch_Stampfenbachstrasse
2024-02-05 05:00:00 → Zch_Stampfenbachstrasse
2024-02-05 06:00:00 → Zch_Stampfenbachstrasse
2024-02-05 07:00:00 → Zch_Stampfenbachstrasse
2024-02-05 08:00:00 → Zch_Stampfenbachstrasse
2024-02-05 09:00:00 → Zch_Stampfenbachstrasse
2024-02-15 14:00:00 → Zch_Rosengartenstrasse
2024-02-15 15:00:00 → Zch_Rosengartenstrasse
2024-03-04 13:00:00 → Zch_Rosengartenstrasse
2024-03-04 14:00:00 → Zch_Rosengartenstrasse
2024-03-28 13:00:00 → Zch_Heubeeribüel
2024-03-28 14:00:00 → Zch_Heubeeribüel
2024-07-12 16:00:00 → Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-12 17:00:00 → Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-19 00:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-19 01:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-19 02:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-19 03:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-19 04:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-19 05:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-19 06:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-19 07:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-19 08:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-19 09:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-19 10:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-19 11:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-19 12:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-19 13:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-19 14:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-19 15:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-19 16:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-19 17:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-19 18:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-19 19:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-19 20:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-19 21:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-19 22:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-19 23:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-20 00:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-20 01:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-20 02:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-20 03:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-20 04:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-20 05:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-20 06:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-20 07:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-20 08:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-20 09:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-20 10:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-20 11:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-20 12:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-20 13:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-20 14:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-20 15:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-20 16:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-20 17:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-20 18:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-20 19:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-20 20:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-20 21:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-20 22:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-20 23:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-21 00:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-21 01:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-21 02:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-21 03:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-21 04:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-21 05:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-21 06:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-21 07:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-21 08:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-21 09:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-21 10:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-21 11:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-21 12:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-21 13:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-21 14:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-21 15:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-21 16:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-21 17:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-21 18:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-21 19:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-21 20:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-21 21:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-21 22:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-21 23:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-22 00:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-22 01:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-22 02:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-22 03:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-22 04:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-22 05:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-22 06:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-22 07:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-22 08:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-22 09:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-22 10:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-22 11:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-22 12:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-22 13:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-22 14:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-22 15:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-22 16:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-22 17:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-22 18:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-22 19:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-22 20:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-22 21:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-22 22:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-22 23:00:00 → Zch_Heubeeribüel, Zch_Rosengartenstrasse, Zch_Schimmelstrasse, Zch_Stampfenbachstrasse
2024-07-24 21:00:00 → Zch_Heubeeribüel
2024-07-24 22:00:00 → Zch_Heubeeribüel
2024-07-24 23:00:00 → Zch_Heubeeribüel
2024-07-25 00:00:00 → Zch_Heubeeribüel
2024-10-24 13:00:00 → Zch_Stampfenbachstrasse
2024-10-24 14:00:00 → Zch_Stampfenbachstrasse

In [ ]:
# Which station-day groups have no valid hourly values for the whole day? -> not possible to calculate daily mean (see error next cell)
g = df_traffic.groupby(["Standort", "Messung_date"])["AnzFahrzeuge"]

summary = (
    g.agg(
        valid_hours=lambda s: s.notna().sum(),
        total_hours="size",
        daily_mean="mean"
    )
    .reset_index()
    .sort_values(["Messung_date", "Standort"])
)

# These are the groups that will produce NaN means (and cause IntCastingNaNError if you cast to int)
all_missing_groups = summary[summary["valid_hours"] == 0]

print(f"# station-day groups with ALL hourly values missing: {len(all_missing_groups)}")
display(all_missing_groups.head(20))

# station-day groups with ALL hourly values missing: 17

,Standort,Messung_date,valid_hours,total_hours,daily_mean
2167,Zch_Stampfenbachstrasse,2024-02-04,0,48,NaN
140,Zch_Heubeeribüel,2024-07-19,0,48,NaN
871,Zch_Rosengartenstrasse,2024-07-19,0,48,NaN
1602,Zch_Schimmelstrasse,2024-07-19,0,48,NaN
2333,Zch_Stampfenbachstrasse,2024-07-19,0,48,NaN
141,Zch_Heubeeribüel,2024-07-20,0,48,NaN
872,Zch_Rosengartenstrasse,2024-07-20,0,48,NaN
1603,Zch_Schimmelstrasse,2024-07-20,0,48,NaN
2334,Zch_Stampfenbachstrasse,2024-07-20,0,48,NaN
142,Zch_Heubeeribüel,2024-07-21,0,48,NaN
873,Zch_Rosengartenstrasse,2024-07-21,0,48,NaN
1604,Zch_Schimmelstrasse,2024-07-21,0,48,NaN
2335,Zch_Stampfenbachstrasse,2024-07-21,0,48,NaN
143,Zch_Heubeeribüel,2024-07-22,0,48,NaN
874,Zch_Rosengartenstrasse,2024-07-22,0,48,NaN
1605,Zch_Schimmelstrasse,2024-07-22,0,48,NaN
2336,Zch_Stampfenbachstrasse,2024-07-22,0,48,NaN

=> delete dates 19.07.2024 - 22.07.2024 for  4 out of 5 stations + additionally 04.02.2024 for one of the five stations

In [104]:

daily_avg = (
    df_traffic
    .groupby(["Standort", "Messung_date"], as_index=False)["AnzFahrzeuge"]
    .mean()
    .round(0)  # round to nearest integer
    .astype({"AnzFahrzeuge": "int"})  # convert to integer type
    .rename(columns={"AnzFahrzeuge": "AnzFahrzeuge_daily_mean"})
)

daily_avg.head()

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer: Error while type casting for column 'AnzFahrzeuge'

In [ ]:
# FIX: delete station-days with all missing hourly values before averaging & rounding
# 1) Daily means + coverage from the original hourly data
daily_qc = (
    df_traffic
    .groupby(["Standort", "Messung_date"])["AnzFahrzeuge"]
    .agg(
        daily_mean="mean",
        valid_hours=lambda s: s.notna().sum(),
        total_hours="size"
    )
    .reset_index()
)

# 2) Exclude full-day outages
daily_kept = daily_qc[daily_qc["valid_hours"] > 0].copy()

# Optional: enforce a minimum coverage (e.g., require ≥ 18 hours)
# min_hours = 18
# daily_kept = daily_kept[daily_kept["valid_hours"] >= min_hours]

# 3) Round the daily mean safely
daily_kept["AnzFahrzeuge_daily_mean"] = (
    pd.Series(daily_kept["daily_mean"]).round(0).astype("Int64")
)

# 4) Average per station over the retained days
station_avg = (
    daily_kept
    .groupby("Standort", as_index=False)["AnzFahrzeuge_daily_mean"]
    .mean()  # could also do median() ...
    .round(0)
    .astype({"AnzFahrzeuge_daily_mean": "Int64"})
    .rename(columns={"AnzFahrzeuge_daily_mean": "AnzFahrzeuge_station_mean"})
)

display(daily_kept)
display(station_avg)

,Standort,Messung_date,daily_mean,valid_hours,total_hours,AnzFahrzeuge_daily_mean
0,Zch_Heubeeribüel,2024-03-01,53.916667,48,48,54
1,Zch_Heubeeribüel,2024-03-02,81.937500,48,48,82
2,Zch_Heubeeribüel,2024-03-03,84.625000,48,48,85
3,Zch_Heubeeribüel,2024-03-04,64.000000,48,48,64
4,Zch_Heubeeribüel,2024-03-05,51.000000,48,48,51
...,...,...,...,...,...,...
2494,Zch_Stampfenbachstrasse,2024-12-27,206.395833,48,48,206
2495,Zch_Stampfenbachstrasse,2024-12-28,180.291667,48,48,180
2496,Zch_Stampfenbachstrasse,2024-12-29,149.020833,48,48,149
2497,Zch_Stampfenbachstrasse,2024-12-30,187.937500,48,48,188
2498,Zch_Stampfenbachstrasse,2024-12-31,170.020833,48,48,170

                  Standort  AnzFahrzeuge_station_mean
0         Zch_Heubeeribüel                         67
1   Zch_Rosengartenstrasse                        975
2      Zch_Schimmelstrasse                        612
3  Zch_Stampfenbachstrasse                        257